CREATE DATABASE B65949_DB_XYZ

CREATE TABLE B65949_CLIENT(
ID SERIAL PRIMARY KEY  NOT NULL,
CLIENT_NAME VARCHAR(50) NOT NULL,
LASTNAME VARCHAR(50) NOT NULL,
AGE INT NOT NULL
)

CREATE TABLE B65949_CLIENT_CREDIT_CARD(
CLIENT_ID INT NOT NULL,
CARD_ID INT NOT NULL,
CREDIT_CARD_NO VARCHAR(255) NOT NULL
)

CREATE TABLE B65949_PURCHASE_ORDER(
CLIENT_PURCHASE_ORDER_ID INT NOT NULL,
CLIENT_ID INT NOT NULL,
ORDER_DESCRIPTION VARCHAR(255) NOT NULL,
AMOUNT INT NOT NULL,
CREDIT_CARD_ID INT NOT NULL
)

CREATE TABLE B65949_CLIENT_PHONE (
CLIENT_PHONE_ID INT NOT NULL,
CLIENT_ID INT NOT NULL,
PHONE_NO VARCHAR(255) NULL
)

CREATE TABLE B65949_CLIENT_ADDRESS (
CLIENT_ADDRESS_ID INT NOT NULL,
CLIENT_ID INT NOT NULL,
CLIENT_ADDRESS VARCHAR(255) NOT NULL
)

CREATE TABLE B65949_CLIENT_EMAIL (
CLIENT_EMAIL_ID INT NOT NULL,
CLIENT_ID INT NOT NULL,
EMAIL VARCHAR(255) NOT NULL
)

ALTER TABLE B65949_CLIENT
ADD SUBMMITTED_DATE DATE 

ALTER TABLE B65949_CLIENT_ADDRESS
ADD SUBMMITTED_DATE DATE

ALTER TABLE B65949_CLIENT_CREDIT_CARD
ADD SUBMMITTED_DATE DATE 

ALTER TABLE B65949_CLIENT_EMAIL
ADD SUBMMITTED_DATE DATE 

ALTER TABLE B65949_CLIENT_PHONE
ADD SUBMMITTED_DATE DATE

ALTER TABLE B65949_PURCHASE_ORDER
ADD SUBMMITTED_DATE DATE